<?php

return [
    'inputs' => [
        'suhu' => [
            'preferred_slug' => 'suhu-udara',
            'labels' => ['Dingin', 'Normal', 'Panas'],
        ],
        'kelembapan_udara' => [
            'preferred_slug' => 'kelembapan-udara',
            'labels' => ['Rendah', 'Sedang', 'Tinggi'],
        ],
        'kelembapan_tanah' => [
            'preferred_slug' => 'kelembapan-tanah',
            'labels' => ['Kering', 'Lembab', 'Basah'],
        ],
        'usia_tanaman' => [
            'preferred_slug' => 'usia-tanaman',
            'labels' => ['Muda', 'Dewasa', 'Tua'],
        ],
    ],
    'output' => [
        'preferred_slug' => 'output',
        'labels' => ['Mati', 'Sedikit', 'Banyak'],
    ],
    'rulebase' => [
        [
            'id' => 1,
            'suhu' => 'Dingin',
            'kelembapan_udara' => 'Rendah',
            'kelembapan_tanah' => 'Kering',
            'usia_tanaman' => 'Muda',
            'output' => 'Banyak',
        ],
        [
            'id' => 2,
            'suhu' => 'Dingin',
            'kelembapan_udara' => 'Rendah',
            'kelembapan_tanah' => 'Kering',
            'usia_tanaman' => 'Dewasa',
            'output' => 'Banyak',
        ],
        [
            'id' => 3,
            'suhu' => 'Dingin',
            'kelembapan_udara' => 'Rendah',
            'kelembapan_tanah' => 'Kering',
            'usia_tanaman' => 'Tua',
            'output' => 'Banyak',
        ],
        [
            'id' => 4,
            'suhu' => 'Dingin',
            'kelembapan_udara' => 'Rendah',
            'kelembapan_tanah' => 'Lembab',
            'usia_tanaman' => 'Muda',
            'output' => 'Sedikit',
        ],
        [
            'id' => 5,
            'suhu' => 'Dingin',
            'kelembapan_udara' => 'Rendah',
            'kelembapan_tanah' => 'Lembab',
            'usia_tanaman' => 'Dewasa',
            'output' => 'Sedikit',
        ],
        [
            'id' => 6,
            'suhu' => 'Dingin',
            'kelembapan_udara' => 'Rendah',
            'kelembapan_tanah' => 'Lembab',
            'usia_tanaman' => 'Tua',
            'output' => 'Sedikit',
        ],
        [
            'id' => 7,
            'suhu' => 'Dingin',
            'kelembapan_udara' => 'Rendah',
            'kelembapan_tanah' => 'Basah',
            'usia_tanaman' => 'Muda',
            'output' => 'Mati',
        ],
        [
            'id' => 8,
            'suhu' => 'Dingin',
            'kelembapan_udara' => 'Rendah',
            'kelembapan_tanah' => 'Basah',
            'usia_tanaman' => 'Dewasa',
            'output' => 'Mati',
        ],
        [
            'id' => 9,
            'suhu' => 'Dingin',
            'kelembapan_udara' => 'Rendah',
            'kelembapan_tanah' => 'Basah',
            'usia_tanaman' => 'Tua',
            'output' => 'Mati',
        ],
        [
            'id' => 10,
            'suhu' => 'Dingin',
            'kelembapan_udara' => 'Sedang',
            'kelembapan_tanah' => 'Kering',
            'usia_tanaman' => 'Muda',
            'output' => 'Sedikit',
        ],
        [
            'id' => 11,
            'suhu' => 'Dingin',
            'kelembapan_udara' => 'Sedang',
            'kelembapan_tanah' => 'Kering',
            'usia_tanaman' => 'Dewasa',
            'output' => 'Banyak',
        ],
        [
            'id' => 12,
            'suhu' => 'Dingin',
            'kelembapan_udara' => 'Sedang',
            'kelembapan_tanah' => 'Kering',
            'usia_tanaman' => 'Tua',
            'output' => 'Banyak',
        ],
        [
            'id' => 13,
            'suhu' => 'Dingin',
            'kelembapan_udara' => 'Sedang',
            'kelembapan_tanah' => 'Lembab',
            'usia_tanaman' => 'Muda',
            'output' => 'Sedikit',
        ],
        [
            'id' => 14,
            'suhu' => 'Dingin',
            'kelembapan_udara' => 'Sedang',
            'kelembapan_tanah' => 'Lembab',
            'usia_tanaman' => 'Dewasa',
            'output' => 'Sedikit',
        ],
        [
            'id' => 15,
            'suhu' => 'Dingin',
            'kelembapan_udara' => 'Sedang',
            'kelembapan_tanah' => 'Lembab',
            'usia_tanaman' => 'Tua',
            'output' => 'Sedikit',
        ],
        [
            'id' => 16,
            'suhu' => 'Dingin',
            'kelembapan_udara' => 'Sedang',
            'kelembapan_tanah' => 'Basah',
            'usia_tanaman' => 'Muda',
            'output' => 'Mati',
        ],
        [
            'id' => 17,
            'suhu' => 'Dingin',
            'kelembapan_udara' => 'Sedang',
            'kelembapan_tanah' => 'Basah',
            'usia_tanaman' => 'Dewasa',
            'output' => 'Mati',
        ],
        [
            'id' => 18,
            'suhu' => 'Dingin',
            'kelembapan_udara' => 'Sedang',
            'kelembapan_tanah' => 'Basah',
            'usia_tanaman' => 'Tua',
            'output' => 'Mati',
        ],
        [
            'id' => 19,
            'suhu' => 'Dingin',
            'kelembapan_udara' => 'Tinggi',
            'kelembapan_tanah' => 'Kering',
            'usia_tanaman' => 'Muda',
            'output' => 'Sedikit',
        ],
        [
            'id' => 20,
            'suhu' => 'Dingin',
            'kelembapan_udara' => 'Tinggi',
            'kelembapan_tanah' => 'Kering',
            'usia_tanaman' => 'Dewasa',
            'output' => 'Sedikit',
        ],
        [
            'id' => 21,
            'suhu' => 'Dingin',
            'kelembapan_udara' => 'Tinggi',
            'kelembapan_tanah' => 'Kering',
            'usia_tanaman' => 'Tua',
            'output' => 'Banyak',
        ],
        [
            'id' => 22,
            'suhu' => 'Dingin',
            'kelembapan_udara' => 'Tinggi',
            'kelembapan_tanah' => 'Lembab',
            'usia_tanaman' => 'Muda',
            'output' => 'Sedikit',
        ],
        [
            'id' => 23,
            'suhu' => 'Dingin',
            'kelembapan_udara' => 'Tinggi',
            'kelembapan_tanah' => 'Lembab',
            'usia_tanaman' => 'Dewasa',
            'output' => 'Sedikit',
        ],
        [
            'id' => 24,
            'suhu' => 'Dingin',
            'kelembapan_udara' => 'Tinggi',
            'kelembapan_tanah' => 'Lembab',
            'usia_tanaman' => 'Tua',
            'output' => 'Sedikit',
        ],
        [
            'id' => 25,
            'suhu' => 'Dingin',
            'kelembapan_udara' => 'Tinggi',
            'kelembapan_tanah' => 'Basah',
            'usia_tanaman' => 'Muda',
            'output' => 'Mati',
        ],
        [
            'id' => 26,
            'suhu' => 'Dingin',
            'kelembapan_udara' => 'Tinggi',
            'kelembapan_tanah' => 'Basah',
            'usia_tanaman' => 'Dewasa',
            'output' => 'Mati',
        ],
        [
            'id' => 27,
            'suhu' => 'Dingin',
            'kelembapan_udara' => 'Tinggi',
            'kelembapan_tanah' => 'Basah',
            'usia_tanaman' => 'Tua',
            'output' => 'Mati',
        ],
        [
            'id' => 28,
            'suhu' => 'Normal',
            'kelembapan_udara' => 'Rendah',
            'kelembapan_tanah' => 'Kering',
            'usia_tanaman' => 'Muda',
            'output' => 'Banyak',
        ],
        [
            'id' => 29,
            'suhu' => 'Normal',
            'kelembapan_udara' => 'Rendah',
            'kelembapan_tanah' => 'Kering',
            'usia_tanaman' => 'Dewasa',
            'output' => 'Banyak',
        ],
        [
            'id' => 30,
            'suhu' => 'Normal',
            'kelembapan_udara' => 'Rendah',
            'kelembapan_tanah' => 'Kering',
            'usia_tanaman' => 'Tua',
            'output' => 'Banyak',
        ],
        [
            'id' => 31,
            'suhu' => 'Normal',
            'kelembapan_udara' => 'Rendah',
            'kelembapan_tanah' => 'Lembab',
            'usia_tanaman' => 'Muda',
            'output' => 'Sedikit',
        ],
        [
            'id' => 32,
            'suhu' => 'Normal',
            'kelembapan_udara' => 'Rendah',
            'kelembapan_tanah' => 'Lembab',
            'usia_tanaman' => 'Dewasa',
            'output' => 'Banyak',
        ],
        [
            'id' => 33,
            'suhu' => 'Normal',
            'kelembapan_udara' => 'Rendah',
            'kelembapan_tanah' => 'Lembab',
            'usia_tanaman' => 'Tua',
            'output' => 'Banyak',
        ],
        [
            'id' => 34,
            'suhu' => 'Normal',
            'kelembapan_udara' => 'Rendah',
            'kelembapan_tanah' => 'Basah',
            'usia_tanaman' => 'Muda',
            'output' => 'Mati',
        ],
        [
            'id' => 35,
            'suhu' => 'Normal',
            'kelembapan_udara' => 'Rendah',
            'kelembapan_tanah' => 'Basah',
            'usia_tanaman' => 'Dewasa',
            'output' => 'Sedikit',
        ],
        [
            'id' => 36,
            'suhu' => 'Normal',
            'kelembapan_udara' => 'Rendah',
            'kelembapan_tanah' => 'Basah',
            'usia_tanaman' => 'Tua',
            'output' => 'Sedikit',
        ],
        [
            'id' => 37,
            'suhu' => 'Normal',
            'kelembapan_udara' => 'Sedang',
            'kelembapan_tanah' => 'Kering',
            'usia_tanaman' => 'Muda',
            'output' => 'Banyak',
        ],
        [
            'id' => 38,
            'suhu' => 'Normal',
            'kelembapan_udara' => 'Sedang',
            'kelembapan_tanah' => 'Kering',
            'usia_tanaman' => 'Dewasa',
            'output' => 'Banyak',
        ],
        [
            'id' => 39,
            'suhu' => 'Normal',
            'kelembapan_udara' => 'Sedang',
            'kelembapan_tanah' => 'Kering',
            'usia_tanaman' => 'Tua',
            'output' => 'Banyak',
        ],
        [
            'id' => 40,
            'suhu' => 'Normal',
            'kelembapan_udara' => 'Sedang',
            'kelembapan_tanah' => 'Lembab',
            'usia_tanaman' => 'Muda',
            'output' => 'Sedikit',
        ],
        [
            'id' => 41,
            'suhu' => 'Normal',
            'kelembapan_udara' => 'Sedang',
            'kelembapan_tanah' => 'Lembab',
            'usia_tanaman' => 'Dewasa',
            'output' => 'Sedikit',
        ],
        [
            'id' => 42,
            'suhu' => 'Normal',
            'kelembapan_udara' => 'Sedang',
            'kelembapan_tanah' => 'Lembab',
            'usia_tanaman' => 'Tua',
            'output' => 'Sedikit',
        ],
        [
            'id' => 43,
            'suhu' => 'Normal',
            'kelembapan_udara' => 'Sedang',
            'kelembapan_tanah' => 'Basah',
            'usia_tanaman' => 'Muda',
            'output' => 'Mati',
        ],
        [
            'id' => 44,
            'suhu' => 'Normal',
            'kelembapan_udara' => 'Sedang',
            'kelembapan_tanah' => 'Basah',
            'usia_tanaman' => 'Dewasa',
            'output' => 'Mati',
        ],
        [
            'id' => 45,
            'suhu' => 'Normal',
            'kelembapan_udara' => 'Sedang',
            'kelembapan_tanah' => 'Basah',
            'usia_tanaman' => 'Tua',
            'output' => 'Mati',
        ],
        [
            'id' => 46,
            'suhu' => 'Normal',
            'kelembapan_udara' => 'Tinggi',
            'kelembapan_tanah' => 'Kering',
            'usia_tanaman' => 'Muda',
            'output' => 'Banyak',
        ],
        [
            'id' => 47,
            'suhu' => 'Normal',
            'kelembapan_udara' => 'Tinggi',
            'kelembapan_tanah' => 'Kering',
            'usia_tanaman' => 'Dewasa',
            'output' => 'Banyak',
        ],
        [
            'id' => 48,
            'suhu' => 'Normal',
            'kelembapan_udara' => 'Tinggi',
            'kelembapan_tanah' => 'Kering',
            'usia_tanaman' => 'Tua',
            'output' => 'Banyak',
        ],
        [
            'id' => 49,
            'suhu' => 'Normal',
            'kelembapan_udara' => 'Tinggi',
            'kelembapan_tanah' => 'Lembab',
            'usia_tanaman' => 'Muda',
            'output' => 'Sedikit',
        ],
        [
            'id' => 50,
            'suhu' => 'Normal',
            'kelembapan_udara' => 'Tinggi',
            'kelembapan_tanah' => 'Lembab',
            'usia_tanaman' => 'Dewasa',
            'output' => 'Sedikit',
        ],
        [
            'id' => 51,
            'suhu' => 'Normal',
            'kelembapan_udara' => 'Tinggi',
            'kelembapan_tanah' => 'Lembab',
            'usia_tanaman' => 'Tua',
            'output' => 'Sedikit',
        ],
        [
            'id' => 52,
            'suhu' => 'Normal',
            'kelembapan_udara' => 'Tinggi',
            'kelembapan_tanah' => 'Basah',
            'usia_tanaman' => 'Muda',
            'output' => 'Mati',
        ],
        [
            'id' => 53,
            'suhu' => 'Normal',
            'kelembapan_udara' => 'Tinggi',
            'kelembapan_tanah' => 'Basah',
            'usia_tanaman' => 'Dewasa',
            'output' => 'Mati',
        ],
        [
            'id' => 54,
            'suhu' => 'Normal',
            'kelembapan_udara' => 'Tinggi',
            'kelembapan_tanah' => 'Basah',
            'usia_tanaman' => 'Tua',
            'output' => 'Mati',
        ],
        [
            'id' => 55,
            'suhu' => 'Panas',
            'kelembapan_udara' => 'Rendah',
            'kelembapan_tanah' => 'Kering',
            'usia_tanaman' => 'Muda',
            'output' => 'Banyak',
        ],
        [
            'id' => 56,
            'suhu' => 'Panas',
            'kelembapan_udara' => 'Rendah',
            'kelembapan_tanah' => 'Kering',
            'usia_tanaman' => 'Dewasa',
            'output' => 'Banyak',
        ],
        [
            'id' => 57,
            'suhu' => 'Panas',
            'kelembapan_udara' => 'Rendah',
            'kelembapan_tanah' => 'Kering',
            'usia_tanaman' => 'Tua',
            'output' => 'Banyak',
        ],
        [
            'id' => 58,
            'suhu' => 'Panas',
            'kelembapan_udara' => 'Rendah',
            'kelembapan_tanah' => 'Lembab',
            'usia_tanaman' => 'Muda',
            'output' => 'Banyak',
        ],
        [
            'id' => 59,
            'suhu' => 'Panas',
            'kelembapan_udara' => 'Rendah',
            'kelembapan_tanah' => 'Lembab',
            'usia_tanaman' => 'Dewasa',
            'output' => 'Banyak',
        ],
        [
            'id' => 60,
            'suhu' => 'Panas',
            'kelembapan_udara' => 'Rendah',
            'kelembapan_tanah' => 'Lembab',
            'usia_tanaman' => 'Tua',
            'output' => 'Banyak',
        ],
        [
            'id' => 61,
            'suhu' => 'Panas',
            'kelembapan_udara' => 'Rendah',
            'kelembapan_tanah' => 'Basah',
            'usia_tanaman' => 'Muda',
            'output' => 'Sedikit',
        ],
        [
            'id' => 62,
            'suhu' => 'Panas',
            'kelembapan_udara' => 'Rendah',
            'kelembapan_tanah' => 'Basah',
            'usia_tanaman' => 'Dewasa',
            'output' => 'Sedikit',
        ],
        [
            'id' => 63,
            'suhu' => 'Panas',
            'kelembapan_udara' => 'Rendah',
            'kelembapan_tanah' => 'Basah',
            'usia_tanaman' => 'Tua',
            'output' => 'Sedikit',
        ],
        [
            'id' => 64,
            'suhu' => 'Panas',
            'kelembapan_udara' => 'Sedang',
            'kelembapan_tanah' => 'Kering',
            'usia_tanaman' => 'Muda',
            'output' => 'Banyak',
        ],
        [
            'id' => 65,
            'suhu' => 'Panas',
            'kelembapan_udara' => 'Sedang',
            'kelembapan_tanah' => 'Kering',
            'usia_tanaman' => 'Dewasa',
            'output' => 'Banyak',
        ],
        [
            'id' => 66,
            'suhu' => 'Panas',
            'kelembapan_udara' => 'Sedang',
            'kelembapan_tanah' => 'Kering',
            'usia_tanaman' => 'Tua',
            'output' => 'Banyak',
        ],
        [
            'id' => 67,
            'suhu' => 'Panas',
            'kelembapan_udara' => 'Sedang',
            'kelembapan_tanah' => 'Lembab',
            'usia_tanaman' => 'Muda',
            'output' => 'Banyak',
        ],
        [
            'id' => 68,
            'suhu' => 'Panas',
            'kelembapan_udara' => 'Sedang',
            'kelembapan_tanah' => 'Lembab',
            'usia_tanaman' => 'Dewasa',
            'output' => 'Banyak',
        ],
        [
            'id' => 69,
            'suhu' => 'Panas',
            'kelembapan_udara' => 'Sedang',
            'kelembapan_tanah' => 'Lembab',
            'usia_tanaman' => 'Tua',
            'output' => 'Banyak',
        ],
        [
            'id' => 70,
            'suhu' => 'Panas',
            'kelembapan_udara' => 'Sedang',
            'kelembapan_tanah' => 'Basah',
            'usia_tanaman' => 'Muda',
            'output' => 'Mati',
        ],
        [
            'id' => 71,
            'suhu' => 'Panas',
            'kelembapan_udara' => 'Sedang',
            'kelembapan_tanah' => 'Basah',
            'usia_tanaman' => 'Dewasa',
            'output' => 'Sedikit',
        ],
        [
            'id' => 72,
            'suhu' => 'Panas',
            'kelembapan_udara' => 'Sedang',
            'kelembapan_tanah' => 'Basah',
            'usia_tanaman' => 'Tua',
            'output' => 'Sedikit',
        ],
        [
            'id' => 73,
            'suhu' => 'Panas',
            'kelembapan_udara' => 'Tinggi',
            'kelembapan_tanah' => 'Kering',
            'usia_tanaman' => 'Muda',
            'output' => 'Banyak',
        ],
        [
            'id' => 74,
            'suhu' => 'Panas',
            'kelembapan_udara' => 'Tinggi',
            'kelembapan_tanah' => 'Kering',
            'usia_tanaman' => 'Dewasa',
            'output' => 'Banyak',
        ],
        [
            'id' => 75,
            'suhu' => 'Panas',
            'kelembapan_udara' => 'Tinggi',
            'kelembapan_tanah' => 'Kering',
            'usia_tanaman' => 'Tua',
            'output' => 'Banyak',
        ],
        [
            'id' => 76,
            'suhu' => 'Panas',
            'kelembapan_udara' => 'Tinggi',
            'kelembapan_tanah' => 'Lembab',
            'usia_tanaman' => 'Muda',
            'output' => 'Sedikit',
        ],
        [
            'id' => 77,
            'suhu' => 'Panas',
            'kelembapan_udara' => 'Tinggi',
            'kelembapan_tanah' => 'Lembab',
            'usia_tanaman' => 'Dewasa',
            'output' => 'Sedikit',
        ],
        [
            'id' => 78,
            'suhu' => 'Panas',
            'kelembapan_udara' => 'Tinggi',
            'kelembapan_tanah' => 'Lembab',
            'usia_tanaman' => 'Tua',
            'output' => 'Banyak',
        ],
        [
            'id' => 79,
            'suhu' => 'Panas',
            'kelembapan_udara' => 'Tinggi',
            'kelembapan_tanah' => 'Basah',
            'usia_tanaman' => 'Muda',
            'output' => 'Mati',
        ],
        [
            'id' => 80,
            'suhu' => 'Panas',
            'kelembapan_udara' => 'Tinggi',
            'kelembapan_tanah' => 'Basah',
            'usia_tanaman' => 'Dewasa',
            'output' => 'Mati',
        ],
        [
            'id' => 81,
            'suhu' => 'Panas',
            'kelembapan_udara' => 'Tinggi',
            'kelembapan_tanah' => 'Basah',
            'usia_tanaman' => 'Tua',
            'output' => 'Mati',
        ],
    ],
];